### ISSUE TITLE
IPv6 PD?

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#24] opened 2021-04-29 02:11 UTC
Hello, would like to know if it possible to add IPv6 PD to DJA0230?

Have a provider saying it should boot up automatically with the ipv6 prefix delegation but I look around DJA0230 and could not find any PD settings nor add it there? Am I missing something?

PD = prefix delegation

**Comment by seud0nym** [comment] 2021-04-29 02:40
Is your IPv6 address static or assigned by your ISP via DHCP?

My ISP assigned it via DHCP. It shows the full address range (mine is /56) on the Internet Access screen, and the range in use by the LAN (the /64 range) on the Local Network screen. With DHCPv6 and RA+SLAAC enabled, my LAN devices all get allocated an IPv6 address.

I have been helping another user who has a static IPv6 address/prefix range, and it seems to be working for him as well.

I think with OpenWRT, delegation is basically automatic, but if you are having issues, I will do a bit more research,.

**Comment by jmytch** [comment] 2021-04-29 03:13
ISP had said we support IPv6 on all connections using DHCP and you may need to select Prefix Delegation (PD) on the router.

Also they have ipv6 config https://launtel.net.au/ipv6-configs/ but unfortunately I cannot get it to work? Any ideas?

The thing is that I have IPv6 enabled which can be seen in screenshot.
![ipv6](https://user-images.githubusercontent.com/45726972/116498212-932ed400-a8ec-11eb-86b8-71aadfc8fbf9.PNG)
![ipv62](https://user-images.githubusercontent.com/45726972/116498213-93c76a80-a8ec-11eb-981f-919a005ac903.PNG)
![ipv63](https://user-images.githubusercontent.com/45726972/116498240-a477e080-a8ec-11eb-9b4f-ca2671f8e0b1.PNG)

**Comment by seud0nym** [comment] 2021-04-29 03:28
On the internet access screen, when you scroll down a bit more, it should show you (beneath IPv4 DNS Servers) the following:

- IPv6 address
- IPv6 Prefix
- IPv6 DNS Servers

Are they all showing addresses? The important ones are the address and the prefix, obviously.

On their config page https://launtel.net.au/ipv6-configs/, the other Technicolor devices mostly seem to say that it works without extra configuration. I assume they are also OpenWRT based, and that is what I would expect.

**Comment by jmytch** [comment] 2021-04-29 03:41
![Capture](https://user-images.githubusercontent.com/45726972/116499502-a68f6e80-a8ef-11eb-8ea4-b8904f3d3f85.PNG)
That is all I can see, and I only use your tch-gui-unhide script that comes with this. I don't see IPv6 address, dns server
![Capture](https://user-images.githubusercontent.com/45726972/116499843-7ac0b880-a8f0-11eb-9460-c0daa28eea8b.PNG)

Something is not right here, I did reset factory to default with root earlier, and try to fix this for hours and can't figure out what is wrong here? I'm not sure if they use OpenWRT

**Comment by seud0nym** [comment] 2021-04-29 03:50
Sorry, I meant that OpenWRT is what the Technicolor devices are based upon.

I don't think there is anything wrong with your configuration. It looks to me like you aren't getting an IPv6 address from your ISP. 

Does your ISP give you the option to "kick" or disconnect the connection from their web site after configuring it for IPv6? If so, do that, then reboot the DJA0230 again. If it still doesn't work, I think you need to get them to check it from their side.

**Comment by jmytch** [comment] 2021-04-29 04:12
I had reboot the modem many times and does not work.

From my portal, IPv6 prefix says it's a /48, does the modem still support /48, and any range I believe?

Other than that, yeah might have to ask to check on their end

**Comment by seud0nym** [comment] 2021-04-29 04:16
Yes, it should support any size range. Mine is a /54 and it works without any problems.

**Comment by jmytch** [comment] 2021-04-29 07:41
They have checked with the network team on their end and was told that it's all looking good. From what they have seen, Telstra modems should pick up the IPv6 config automatically.

Any CL i could try in the putty by any chance to request ipv6 or something on modem's end?

**Comment by seud0nym** [comment] 2021-04-29 08:45
What does the following command return?

`transformer-cli get uci.network.interface.@wan.ipv6`

**Comment by jmytch** [comment] 2021-04-29 09:30
```
root@mymodem:~# transformer-cli get uci.network.interface.@wan.ipv6
uci.network.interface.@wan.ipv6 [string] = 1
```
I guess 1 means enabled?

**Comment by seud0nym** [comment] 2021-04-29 12:23
Yes. It was a long shot...

Just as a test: if you turn off IPv6 Force Prefix, do you get an IPv6 address?

**Comment by jmytch** [comment] 2021-04-29 12:57
Unfortunately not :(

**Comment by seud0nym** [comment] 2021-04-30 02:37
What firmware are you running on your DJA0230? I will get out my spare and configure it up to see whether I have the same problem (my normal router is a DJA0231).

**Comment by jmytch** [comment] 2021-04-30 02:39
tch-gui-unhide 2021.04.01 for FW Version 18.1.c.0549

**Comment by seud0nym** [comment] 2021-04-30 05:00
Initial test: 

I re-applied `tch-gui-unhide 2021-04-01` to my test DJA0230, then I swapped the ethernet cable out of my HFC NTD from the DJA0231 to DJA0230. It took quite a while, but eventually it got an IPv4 address, but no IPv6. So, I was able reproduce what you are seeing.

Second test: 
- I ran `reset-to-factory-defaults` (I used the `-i` option to keep my test IP address so it doesn't conflict with my normal LAN settings), and after it rebooted, it got an IPv6 address and prefix! (i.e. running on the stock GUI). I could see this by running the command: `ip -o a | grep eth4`. 
- I then applied `tch-gui-unhide 2021-04-01` (with no options except `-y`) and rebooted - still had IPv6.
- I then ran `./de-telstra -A` and rebooted - still had IPv6.
- I then disabled WAN Supervision and supervision in the Internet Access screen, and I re-applied `./tch-gui-unhide -hd -y `. I still have IPv6.

So, after seeing the same thing initially, it is all working correctly. I cannot explain why it isn't working for you.

Are you running `de-telstra`? What options are you using?

What options are you using to `tch-gui-unhide`?

Have you got WAN Sensing enabled or disabled?

What does the log show? i.e. try running `logread -e wan6`

**Comment by jmytch** [comment] 2021-04-30 06:10
Interesting, maybe I should try follow your second test steps and see if that helps. 

Yes I did run de-telstra but never used the `-A` after it. With de-telstra I just let it run everything to remove it from the modem.

The only things I had changed after adding tch-gui-unhide is just disabling the WiFi Booster and Mobile (LTE) as well disabled WAN Supervision too. WAN Sensing is disabled, and set to `VDSL2` since I don't have a sim card in the modem so it pointless to have it enabled? No other options had been used beside those.

Here is the log as requested (did not reset to factory defaults yet)

```
root@mymodem:~# logread -e wan6
Thu Apr 29 22:54:49 2021 daemon.notice netifd: Interface 'wan6' is enabled
Thu Apr 29 22:54:49 2021 daemon.notice netifd: Interface 'wan6' has link connectivity
Thu Apr 29 22:54:49 2021 daemon.notice netifd: Interface 'wan6' is setting up now
Thu Apr 29 22:57:12 2021 daemon.notice netifd: Interface 'wan6' is now down
Thu Apr 29 22:57:12 2021 daemon.notice netifd: Interface 'wan6' has link connectivity loss
Thu Apr 29 22:57:12 2021 daemon.notice netifd: Interface 'wan6' has link connectivity
Thu Apr 29 22:57:12 2021 daemon.notice netifd: Interface 'wan6' is setting up now
Thu Apr 29 22:57:12 2021 user.notice pppoe-relay-hotplug: Interface wan6 ifup-failed

```

**Comment by jmytch** [comment] 2021-04-30 07:30
I did these;

`reset-to-factory-defaults-with-root -i` and after it reboot, it did not get ipv6 however I tried the command that you mentioned `ip -o a | grep eth4` does not work in my putty as nothing shows up? I'm on VDSL2 (FTTN) and DHCP (IPoE) connection. 

I don't know why it did not get ipv6, do you recommend me to reset to factory defaults without the root?

**Comment by seud0nym** [comment] 2021-04-30 08:12
Sorry. I should have asked about connection type. Just do `ip -o a` and look for IPv6 addresses. 

There is no real benefit to a standard RTFD and re-root. It is effectively the same using the script,  just less hassle.

**Comment by jmytch** [comment] 2021-04-30 08:35
It shows IPv6 address in the /64 range, but nothing with the /48 range I was provided by the ISP.

Those /64 ranges are toward wifi and lan. Not the global ptm0 so I'm not sure if the modem really support the /48 range for IPv6.

Other than that, I did follow your steps but doesn't show IPv6 at all

**Comment by jmytch** [comment] 2021-04-30 10:04
Finally after the long figuring out stuff, I've decided to research OpenWRT wan6 for ipv6 and mess around with network config which I pull out with WinSCP. Now for comparsion

Your file contain;
```
config interface 'wan6'
	option reqaddress 'force'
	option forceprefix '1'
```

----
New file with recommendation from OpenWRT
```
config interface 'wan6'
	option reqaddress '**try**'
	**option reqprefix 'auto'**
	option forceprefix '0'
```

So rather the `reqaddress 'force'`, change it into `option reqaddress 'try'` and `option reqprefix 'auto'` does the trick and now got all the IPv6 showing, and tested ipv6 on website to ensure it working that says 10/10 from https://test-ipv6.com/

![Capture](https://user-images.githubusercontent.com/45726972/116680628-3bc55c80-a9ef-11eb-9790-6dbf543f94b1.PNG)
![Capture2](https://user-images.githubusercontent.com/45726972/116680631-3cf68980-a9ef-11eb-8f55-b51b9b58912e.PNG)
![Capture3](https://user-images.githubusercontent.com/45726972/116680638-3e27b680-a9ef-11eb-8911-11a057ff7d55.PNG)

**Comment by seud0nym** [comment] 2021-04-30 12:12
Well done! I am glad you worked it out.

I don't actually change our set those (except for forceprefix). Those are the Telstra defaults.

I will look at updating those screens to allow those config options to be tweaked.

**Comment by jmytch** [comment] 2021-04-30 13:05
> I will look at updating those screens to allow those config options to be tweaked.

That would be a good idea :) 

Since I solve it, you can close this if you want.

**Comment by jmytch** [comment] 2021-05-01 00:28
Ok I have new issue with the hop ipv6 thingy, not sure how to get this to work. 
![Capture](https://user-images.githubusercontent.com/45726972/116765327-e5e0cb00-aa67-11eb-80e6-8b8ef8df0b20.PNG)

**Comment by seud0nym** [comment] 2021-05-01 00:49
There is nothing you can do about that. It depends upon whether Launtel has allowed ping responses from those hosts, which in your case it looks like they haven't. A lot of servers will not answer pings.

When I run the connection check, I get a Next Hop Ping success, but the DNS Servers fail.

Google does give ping responses, so you can check IPv6 pings from the 'Ping & Traceroute' tab in Diagnostics. Set it to protocol IPv6 and enter `google.com` as the host.

I will wait to close this issue until after I have updated the screens with the new field. Also, It looks like `option reqprefix 'auto'` is the default value.

**Comment by seud0nym** [comment] 2021-05-01 08:10
Fixed in next release

**Closed by seud0nym** 2021-05-01 08:10 UTC
