### ISSUE TITLE
Upgrade GUI from 20240229 to 20240531 

### ISSUE THREAD

**Issue by bravohe** [seud0nym/tch-gui-unhide#200] opened 2024-06-03 09:17 UTC
@Technicolor DJN2130 
@Firmware: 17.2.0284-820-RA

I have received the following error message after upgrade GUI from 20240229 to 20240531 

/www/lua/wanservices-ddns_helper.lua:105: table index is nil
stack traceback:
	[string "/gateway.lp"]:162: in function <[string "/gateway.lp"]:161>
	/www/lua/wanservices-ddns_helper.lua:105: in function 'get_services_status'
	/www/lua/wanservicescard_helper.lua:24: in function 'getWANServicesCardHTML'
	[string "014_wanservices.lp"]:8: in function 'content'
	/usr/lib/lua/web/lp.lua:171: in function 'include'
	[string "/gateway.lp"]:160: in function <[string "/gateway.lp"]:159>
	[C]: in function 'xpcall'
	[string "/gateway.lp"]:159: in function 'content'
	/usr/lib/lua/web/web.lua:249: in function 'process'
	content_by_lua(nginx.conf:99):4: in function

**Comment by seud0nym** [comment] 2024-06-03 10:45
Duplicate of #199

**Closed by seud0nym** 2024-06-03 10:45 UTC

**Comment by seud0nym** [comment] 2024-06-03 23:19
I think I have fixed the problem. You can apply the fix with the following command:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```
